title: Autosuggest JS SDK
description: JavaScript SDK for Autosuggest by Unbxd
remote_theme: just-the-docs/just-the-docs

url: https://unbxd.github.io
baseurl: /autosuggest-js-sdk-docs

logo: "/assets/images/logo.svg"

back_to_top: true
back_to_top_text: "Back to top"

enable_copy_code_button: true

footer_content: >
  Copyright Â© 2026
  <a href="https://unbxd.com/" target="_blank">Unbxd</a>.
  All rights reserved.

aux_links:
  "View on GitHub":
    - "https://github.com/unbxd/autosuggest-js-sdk/"

aux_links_new_tab: true

nav_external_links:
  - title: View on GitHub
    url: https://github.com/unbxd/autosuggest-js-sdk/

gh_edit_link: true
gh_edit_link_text: "Edit this page on GitHub"
gh_edit_repository: "https://github.com/unbxd/autosuggest-js-sdk"
gh_edit_branch: "documentation"
gh_edit_view_mode: "edit"

plugins:
  - jekyll-remote-theme
    
